### ISSUE TITLE
Facing error on MacBook Pro M1

### ISSUE THREAD

**Issue by tomtomtls** [kairoh/studio#11]
### Discussed in https://github.com/kairoh/studio/discussions/10

<div type='discussions-op-text'>

<sup>Originally posted by **tomtomtls** September 20, 2022</sup>
Hello, Studio was working great on my previous MecBook Pro (2016 Intel core model). I switched to a M1 model last week, installed the Lunii store, OpenJDK 11, and when now when I try to launch Studio 0.4.2 I face this error:

`[ERROR] [i.v.c.i.l.c.VertxIsolatedDeployer]: Failed in deploying verticle
java.lang.ExceptionInInitializerError
	at studio.driver.LibUsbDetectionHelper.initializeLibUsb(LibUsbDetectionHelper.java:61)
	at studio.driver.raw.RawStoryTellerAsyncDriver.<init>(RawStoryTellerAsyncDriver.java:66)
	at studio.webui.service.StoryTellerService.<init>(StoryTellerService.java:57)
	at studio.webui.MainVerticle.start(MainVerticle.java:66)
	at io.vertx.core.AbstractVerticle.start(AbstractVerticle.java:106)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$5(DeploymentManager.java:196)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:100)
	at io.vertx.core.impl.AbstractContext.dispatch(AbstractContext.java:63)
	at io.vertx.core.impl.EventLoopContext.lambda$runOnContext$0(EventLoopContext.java:38)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:469)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:503)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:829)
Caused by: org.usb4java.LoaderException: Native library not found in classpath: /org/usb4java/darwin-aarch64/libusb4java.dylib
	at org.usb4java.Loader.extractLibrary(Loader.java:246)
	at org.usb4java.Loader.load(Loader.java:323)
	at org.usb4java.LibUsb.<clinit>(LibUsb.java:690)`

I guess it is linked to AARCH64. Do you have any clue to get Studio working again? Many thanks for your help!</div>

**Comment by kairoh** [comment]
Should be fixed in 1.0.0

**Comment by tomtomtls** [comment]
Thank you very much 👍🏼
