### ISSUE TITLE
 Unsupported device metadata format version: 6

### ISSUE THREAD

**Issue by r4cker** [kairoh/studio#110]
I connected a brand new Lunii wifi Wifi and usb C (old one broken) and I have this message

```
2023-09-03 19:06:26,477 [ERROR] [s.w.s.StoryTellerService]: Failed to plug device 2.x
studio.core.v1.utils.exception.StoryTellerException: Unsupported device metadata format version: 6
        at studio.driver.fs.FsStoryTellerAsyncDriver.getDeviceInfos(FsStoryTellerAsyncDriver.java:128)
        at studio.webui.service.StoryTellerService.lambda$new$5(StoryTellerService.java:99)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source)
        at java.base/java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinTask.doExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.scan(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(Unknown Source)
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source)
```

**Comment by hackteur** [comment]
Same problem with Lunii v3

**Comment by ex23** [comment]
Same problem here too with a new Lunii v3.

Is STUdio compatible with the Lunii v3 ???

**Comment by djcaesar9114** [comment]
Same problem here too.
