### ISSUE TITLE
Échec du rafraichissement de la bibliothèque

### ISSUE THREAD

**Issue by Rubbilupin** [kairoh/studio#150]
**Describe the bug**
la bibliothèque ne s'actualise pa set il est impossible de transfére des histoires sur la lunii

**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
2023-11-25 19:37:56,136 INFO  [stu.web.Studio] (main) Running Studio
2023-11-25 19:37:56,485 INFO  [stu.web.api.SockJsEventBusBridge] (main) Start Sockjs EventBus
2023-11-25 19:37:56,488 INFO  [stu.web.ser.LibraryService] (main) library path : ./library (tmpdir path : ./tmp)
2023-11-25 19:37:56,489 INFO  [stu.web.Studio] (main) Opening URL http://localhost:8080/ in default browser...
2023-11-25 19:37:56,507 INFO  [stu.met.DatabaseMetadataService] (main) Read database ./db/unofficial.json
2023-11-25 19:37:56,534 INFO  [stu.met.DatabaseMetadataService] (main) Read database ./db/official.json
2023-11-25 19:37:56,543 INFO  [stu.met.DatabaseMetadataService] (main) Clean official packs in library database
2023-11-25 19:37:56,551 INFO  [io.quarkus] (main) studio-web-ui 1.0.2 native (powered by Quarkus 2.15.3.Final) started in 0.404s. Listening on: http://localhost:8080
2023-11-25 19:37:56,552 INFO  [io.quarkus] (main) Profile prod activated. 
2023-11-25 19:37:56,552 INFO  [io.quarkus] (main) Installed features: [awt, cdi, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, usb4java, vertx]
2023-11-25 19:37:59,412 INFO  [stu.web.ser.StoryTellerService] (vert.x-eventloop-thread-0) Setting up story teller driver
2023-11-25 19:37:59,413 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-0) Initializing libusb...
2023-11-25 19:37:59,431 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-0) Hotplug is supported. Registering hotplug callback(s)...
2023-11-25 19:37:59,431 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-0) Initializing libusb...
2023-11-25 19:37:59,434 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-0) Hotplug is supported. Registering hotplug callback(s)...
2023-11-25 19:37:59,434 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-0) Hotplug event callback (3141:26688): 1
2023-11-25 19:37:59,794 INFO  [stu.dri.ser.fs.FsStoryTellerAsyncDriver] (ForkJoinPool.commonPool-worker-1) FS device partition located: /Volumes/LUNII
2023-11-25 19:38:00,247 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: Suzane_et_Gaston_à_Rome-d16658d2-59d7-4e50-8262-fd60923947ea-v2.zip
2023-11-25 19:38:00,260 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata RAW from pack: 07a2efe5-81fd-4be4-9259-da1b72f9cc3f.converted_1700858187968.pack
2023-11-25 19:38:00,265 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: Alice au pays des merveilles.zip
2023-11-25 19:38:00,277 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: Carnaval_et_confettis-20fdab11-c082-4b09-9178-b0d2c35f5b7f-v1.zip
2023-11-25 19:38:00,284 INFO  [stu.web.api.SockJsEventBusBridge] (vert.x-eventloop-thread-2) Sockjs open
2023-11-25 19:38:00,295 INFO  [stu.met.DatabaseMetadataService] (executor-thread-0) Cache updating of 20fdab11-c082-4b09-9178-b0d2c35f5b7f
2023-11-25 19:38:00,298 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata FS from pack: d16658d2-59d7-4e50-8262-fd60923947ea.converted_1700858316625
2023-11-25 19:38:00,300 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: Contes_des_enfants_extraordinaires-37da5a09-79cc-4de0-9af3-e83cc6ae3071-v1.zip
2023-11-25 19:38:00,335 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata FS from pack: e3c6abcc-f240-4d5d-b7be-4b02c890d437.converted_1700858496236
2023-11-25 19:38:00,347 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata FS from pack: 589934ab-770c-4d29-b0d3-974501f8aeab.converted_1700858282654
2023-11-25 19:38:00,354 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: Les bandes à écouter de Yakari.zip
2023-11-25 19:38:00,359 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-0) HTTP Request to /api/library/packs failed, error id: 6c5ea774-45b3-4370-a765-99235de3e837-1: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: studio.core.v1.exception.StoryTellerException: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:27)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@17.0.5/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:80)
	at studio.webui.service.LibraryService_ClientProxy.packs(Unknown Source)
	at studio.webui.api.LibraryController.lambda$packs$0(LibraryController.java:53)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 9 more
Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.checkUTF8(ZipFileSystem.java:1613)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1584)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base@17.0.5/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base@17.0.5/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
	at studio.core.v1.service.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:33)
	at studio.webui.service.LibraryService.readMetadata(LibraryService.java:140)
	at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:24)
	... 23 more

2023-11-25 19:38:00,361 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-0) Request failed: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
	at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
	at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
	at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
	at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
	at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: studio.core.v1.exception.StoryTellerException: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:27)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base@17.0.5/java.util.Iterator.forEachRemaining(Iterator.java:133)
	at java.base@17.0.5/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at studio.webui.service.LibraryService.packs(LibraryService.java:80)
	at studio.webui.service.LibraryService_ClientProxy.packs(Unknown Source)
	at studio.webui.api.LibraryController.lambda$packs$0(LibraryController.java:53)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
	... 9 more
Caused by: java.util.zip.ZipException: invalid CEN header (bad entry name)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.checkUTF8(ZipFileSystem.java:1613)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.initCEN(ZipFileSystem.java:1584)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystem.<init>(ZipFileSystem.java:179)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystemProvider.getZipFileSystem(ZipFileSystemProvider.java:125)
	at jdk.zipfs@17.0.5/jdk.nio.zipfs.ZipFileSystemProvider.newFileSystem(ZipFileSystemProvider.java:120)
	at java.base@17.0.5/java.nio.file.FileSystems.newFileSystem(FileSystems.java:528)
	at java.base@17.0.5/java.nio.file.FileSystems.newFileSystem(FileSystems.java:400)
	at studio.core.v1.service.archive.ArchiveStoryPackReader.readMetadata(ArchiveStoryPackReader.java:33)
	at studio.webui.service.LibraryService.readMetadata(LibraryService.java:140)
	at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:24)
	... 23 more

2023-11-25 19:38:00,796 INFO  [stu.web.ser.StoryTellerService] (ForkJoinPool.commonPool-worker-1) Device plugged

> Internal Server Error: {"details":"Error id 6c5ea774-45b3-4370-a765-99235de3e837-5","stack":""}

**Desktop and environment (please complete the following information):**
 - OS: MacIntel
 - Browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/119.0.0.0 Safari/537.36
 - Java version: [e.g. JDK 11.0.6]
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 1.0.2

**Additional context**

**Comment by yquenechdu** [comment]
meme problème
