### ISSUE TITLE
STUdio impossible d'importer un pack d'histoire

### ISSUE THREAD

**Issue by jinrohh** [kairoh/studio#203]
Bonjour,

J'ai trouvé un pack d'histoire pour le lecteur d'histoires Lunii sur le net, que l'on peut ajouter sur l'appareil en passant par l'appli web STUdio.

Après avoir installé STUdio en suivant les instructions, branché la Lunii, j'arrive sur bien sur l'onglet STUdio dans firefox, je vois les histoires stockées sur l'appareil, mais impossible d'y ajouter le pack au format .zip.

Que ce soir en glissant le fichier ZIP ou en l'important via la fonction de STUdio, le téléversement fonctionne, mais l'appli indique :
![image](https://github.com/user-attachments/assets/e94dbb8d-14d9-458d-b02e-03217e3ebd43)
Echec de la récupération des packs d'histoire de la bibliothèque.

Ci dessous la copie de la boite de dialogue "DOS"

2024-09-19 15:54:04,734 INFO  [stu.web.Studio] (main) Running Studio
2024-09-19 15:54:04,809 INFO  [stu.web.api.SockJsEventBusBridge] (main) Start Sockjs EventBus
2024-09-19 15:54:04,809 INFO  [stu.web.Studio] (main) Opening URL http://localhost:8080/ in default browser...
2024-09-19 15:54:04,813 INFO  [stu.web.ser.LibraryService] (main) library path : .\library (tmpdir path : .\tmp)
2024-09-19 15:54:04,817 INFO  [stu.met.DatabaseMetadataService] (main) Read database .\db\unofficial.json
2024-09-19 15:54:04,821 INFO  [stu.met.DatabaseMetadataService] (main) Read database .\db\official.json
2024-09-19 15:54:04,825 INFO  [stu.met.DatabaseMetadataService] (main) Clean official packs in library database
2024-09-19 15:54:04,825 INFO  [io.quarkus] (main) studio-web-ui 1.0.2 native (powered by Quarkus 2.15.3.Final) started in 0.093s. Listening on: http://localhost:8080
2024-09-19 15:54:04,829 INFO  [io.quarkus] (main) Profile prod activated.
2024-09-19 15:54:04,829 INFO  [io.quarkus] (main) Installed features: [awt, cdi, rest-client-reactive, rest-client-reactive-jackson, resteasy-reactive, resteasy-reactive-jackson, smallrye-context-propagation, usb4java, vertx]
2024-09-19 15:54:05,387 INFO  [stu.web.ser.StoryTellerService] (vert.x-eventloop-thread-2) Setting up story teller driver
2024-09-19 15:54:05,388 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-2) Initializing libusb...
2024-09-19 15:54:05,394 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-2) Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-09-19 15:54:05,394 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-2) Initializing libusb...
2024-09-19 15:54:05,398 INFO  [stu.dri.usb.LibUsbDetectionHelper] (vert.x-eventloop-thread-2) Hotplug is NOT supported. Scheduling task to actively poll USB device...
2024-09-19 15:54:05,418 INFO  [stu.web.ser.LibraryService] (executor-thread-0) Read metadata ARCHIVE from pack: 358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
2024-09-19 15:54:05,418 INFO  [stu.web.api.SockJsEventBusBridge] (vert.x-eventloop-thread-3) Sockjs open
2024-09-19 15:54:05,421 ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-1) HTTP Request to /api/library/packs failed, error id: 4c9bb53c-69aa-4b25-b107-7f19bed457cc-1: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
Caused by: studio.core.v1.exception.StoryTellerException: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:27)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.5/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@17.0.5/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at studio.webui.service.LibraryService.packs(LibraryService.java:80)
        at studio.webui.service.LibraryService_ClientProxy.packs(Unknown Source)
        at studio.webui.api.LibraryController.lambda$packs$0(LibraryController.java:53)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 9 more
Caused by: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at studio.webui.service.LibraryService.readMetadata(LibraryService.java:142)
        at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:24)
        ... 23 more

2024-09-19 15:54:05,422 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-1) Request failed: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770)
        at io.quarkus.vertx.core.runtime.VertxCoreRecorder$14.runWith(VertxCoreRecorder.java:576)
        at org.jboss.threads.EnhancedQueueExecutor$Task.run(EnhancedQueueExecutor.java:2449)
        at org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1478)
        at org.jboss.threads.DelegatingRunnable.run(DelegatingRunnable.java:29)
        at org.jboss.threads.ThreadLocalResettingRunnable.run(ThreadLocalResettingRunnable.java:29)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.base@17.0.5/java.lang.Thread.run(Thread.java:833)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
Caused by: studio.core.v1.exception.StoryTellerException: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:27)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
        at java.base@17.0.5/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
        at java.base@17.0.5/java.util.Iterator.forEachRemaining(Iterator.java:133)
        at java.base@17.0.5/java.util.Spliterators$IteratorSpliterator.forEachRemaining(Spliterators.java:1845)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
        at java.base@17.0.5/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
        at java.base@17.0.5/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base@17.0.5/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
        at studio.webui.service.LibraryService.packs(LibraryService.java:80)
        at studio.webui.service.LibraryService_ClientProxy.packs(Unknown Source)
        at studio.webui.api.LibraryController.lambda$packs$0(LibraryController.java:53)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768)
        ... 9 more
Caused by: studio.core.v1.exception.StoryTellerException: No metadata found for pack .\library\358f544c-59d6-493e-8c6e-1fe9bb5ef825.zip
        at studio.webui.service.LibraryService.readMetadata(LibraryService.java:142)
        at studio.core.v1.utils.stream.ThrowingFunction.lambda$unchecked$0(ThrowingFunction.java:24)
        ... 23 more

2024-09-19 15:54:05,428 INFO  [stu.dri.usb.LibUsbActivePollingWorker] (pool-7-thread-1) Active polling found a new device. Firing event.
2024-09-19 15:54:05,431 INFO  [stu.dri.ser.fs.FsStoryTellerAsyncDriver] (ForkJoinPool.commonPool-worker-1) FS device partition located: E:\
2024-09-19 15:54:06,446 INFO  [stu.web.ser.StoryTellerService] (ForkJoinPool.commonPool-worker-1) Device plugged

 - OS: Win10
 - Browser Firefox/130.01(64)
 - Java version: [e.g. JDK 11.0.6]
 - STUdio application version: 1.0.2

J'ai également essayé avec chrome..

Merci d'avance pour vos réponses.

**Comment by Westside76** [comment]
Bonjour peux tu me dire ou trouver la version est 1.0.2 ?

**Comment by jinrohh** [comment]
Désolé pour ma réponse (très) tardive, il me semble que je l'ai trouvée ici même.
