### ISSUE TITLE
Drag and drop errors

### ISSUE THREAD

**Issue by AnTeBiOss** [kairoh/studio#49]
error given when download pack to Lunii by drag and drop
ERROR [io.qua.ver.htt.run.QuarkusErrorHandler] (vert.x-eventloop-thread-3) HTTP Request to /api/device/addFromLibrary failed, error id: 2bb65440-c8c6-4342-8e11-e704cb83eabf-2: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: Failed to check device space
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base@17.0.5/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: studio.core.v1.exception.StoryTellerException: Failed to check device space
	at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:384)
	at studio.webui.service.StoryTellerService.upload(StoryTellerService.java:174)
	at studio.webui.service.StoryTellerService.lambda$addPack$3(StoryTellerService.java:116)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 10 more
Caused by: java.nio.file.NoSuchFileException: ./library/./library/79c3b2b7-163e-4b3d-92d8-f8b63021cc85.converted_1676800914176
	at java.base@17.0.5/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base@17.0.5/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base@17.0.5/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base@17.0.5/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3918)
	at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3973)
	at studio.core.v1.utils.io.FileUtils.getFolderSize(FileUtils.java:42)
	at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:371)
	... 13 more

2023-02-19 11:01:54,874 ERROR [org.jbo.res.rea.com.cor.AbstractResteasyReactiveContext] (vert.x-eventloop-thread-3) Request failed: java.util.concurrent.CompletionException: studio.core.v1.exception.StoryTellerException: Failed to check device space
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:510)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1773)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760)
	at java.base@17.0.5/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
	at org.graalvm.nativeimage.builder/com.oracle.svm.core.posix.thread.PosixPlatformThreads.pthreadStartRoutine(PosixPlatformThreads.java:203)
Caused by: studio.core.v1.exception.StoryTellerException: Failed to check device space
	at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:384)
	at studio.webui.service.StoryTellerService.upload(StoryTellerService.java:174)
	at studio.webui.service.StoryTellerService.lambda$addPack$3(StoryTellerService.java:116)
	at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
	... 10 more
Caused by: java.nio.file.NoSuchFileException: ./library/./library/79c3b2b7-163e-4b3d-92d8-f8b63021cc85.converted_1676800914176
	at java.base@17.0.5/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base@17.0.5/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:148)
	at java.base@17.0.5/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base@17.0.5/java.nio.file.Files.readAttributes(Files.java:1851)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.getAttributes(FileTreeWalker.java:220)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.visit(FileTreeWalker.java:277)
	at java.base@17.0.5/java.nio.file.FileTreeWalker.walk(FileTreeWalker.java:323)
	at java.base@17.0.5/java.nio.file.FileTreeIterator.<init>(FileTreeIterator.java:71)
	at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3918)
	at java.base@17.0.5/java.nio.file.Files.walk(Files.java:3973)
	at studio.core.v1.utils.io.FileUtils.getFolderSize(FileUtils.java:42)
	at studio.driver.service.fs.FsStoryTellerAsyncDriver.uploadPack(FsStoryTellerAsyncDriver.java:371)
	... 13 more

**Desktop and environment (please complete the following information):**
 - OS: Linux x86_64
 - Browser Chrome/110.0.0.0 
 - Java version: 17
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 1.0.2

**Additional context**

**Comment by AnTeBiOss** [comment]
please don't care, it perfectly works with the runner app

Thank you for your work !!
