### ISSUE TITLE
pack unable to be added on Lunii with Studio

### ISSUE THREAD

**Issue by patrickderrien** [kairoh/studio#91]
**Describe the bug**
pack unable to be added on Lunii with Studio
**To Reproduce**

**Expected behavior**

**Screenshots**

**Logs**
2023-07-12 12:22:49,540 INFO  [stu.web.api.DeviceController] (vert.x-eventloop-thread-0) addFromLibrary : DeviceDTOs.UuidDTO(uuid=1E038061, path=1E038061, driver=null)
2023-07-12 12:23:07,373 ERROR [stu.web.ser.StoryTellerService] (ForkJoinPool.commonPool-worker-4) Failed to transfer pack: java.util.concurrent.CompletionException: java.lang.IllegalArgumentException: Invalid UUID string: 1E038061
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:649)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$Completion.exec(CompletableFuture.java:483)
        at java.base@17.0.5/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
        at java.base@17.0.5/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
        at java.base@17.0.5/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.thread.PlatformThreads.threadStartRoutine(PlatformThreads.java:775)
        at org.graalvm.nativeimage.builder/com.oracle.svm.core.windows.WindowsPlatformThreads.osThreadStartRoutine(WindowsPlatformThreads.java:178)
Caused by: java.lang.IllegalArgumentException: Invalid UUID string: 1E038061
        at java.base@17.0.5/java.util.UUID.fromString1(UUID.java:280)
        at java.base@17.0.5/java.util.UUID.fromString(UUID.java:258)
        at studio.driver.service.fs.FsStoryTellerAsyncDriver.lambda$uploadPack$18(FsStoryTellerAsyncDriver.java:415)
        at java.base@17.0.5/java.util.concurrent.CompletableFuture$UniApply.tryFire(CompletableFuture.java:646)
        ... 8 more

**Desktop and environment (please complete the following information):**
 - OS: Windows 11 64
 - Opera Version :99.0.4788.88
 - Java version: 8 371
 - Maven version: [e.g. 3.6.0]
 - STUdio application version: 1.0.2

**Additional context**

**Comment by NSV** [comment]
java.lang.IllegalArgumentException: Invalid UUID string: 1E038061

What pack do you try to load ?
